# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestDebugger():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testDebugger(self):
        # Test name: Test-Debugger
        # Step # | name | target | value
        # 1 | open | https://testpages.herokuapp.com/styled/index.html |
        self.driver.get("https://testpages.herokuapp.com/styled/index.html")
        # 2 | setWindowSize | 943x1055 |
        self.driver.set_window_size(943, 1055)
        # 3 | click | id=htmlformtest |
        self.driver.find_element(By.ID, "htmlformtest").click()
        # 4 | addSelection | name=multipleselect[] | label=Selection Item 5
        dropdown = self.driver.find_element(By.NAME, "multipleselect[]")
        dropdown.find_element(By.XPATH, "//option[. = 'Selection Item 5']").click()
        # 5 | removeSelection | name=multipleselect[] | label=Selection Item 4
        dropdown = self.driver.find_element(By.NAME, "multipleselect[]")
        dropdown.find_element(By.XPATH, "//option[. = 'Selection Item 4']").click()
        # 6 | click | xpath=(//input[@name='submitbutton'])[2] |
        self.driver.find_element(By.XPATH, "(//input[@name=\'submitbutton\'])[2]").click()
        # 7 | click | id=back_to_form |
        self.driver.find_element(By.ID, "back_to_form").click()
